### ISSUE TITLE
Fingerprint issue after upd to MIUI 13

### ISSUE THREAD

**Issue by ItsMARCky** [RicardoGuariento/MIUI-XML-13-BRAZILIAN#1]
After the update to the MIUI 13 version, my bluetooth sensor stopped working, I've already cleaned the cache, I've tested all the procedures I found on the internet and so far I still don't have the sensor, the only test that unfortunately I can't do is the reset factory, because I have my company's VPN application installed on it, and I have to open a ticket to be able to recreate an access PIN, which takes an average of around 5 days and as I am working at Home Office, this option would cause me inconvenience , would you have any suggestions please without formatting the cell phone?

I updated to MIUI Global version 13.0.3 and already had an update to version 13.0.4.

**Comment by ItsMARCky** [comment]
Sorry, forgot to mention, my phone is a Poco F3.

**Comment by DiorgenesS** [comment]
Aqui somos responsáveis apenas pelos erros de tradução do idioma PT-BR na ROM Europeia (xiaomi.eu).
