### ISSUE TITLE
Add a collaborator

### ISSUE THREAD

**Issue by ingbrzy** [RicardoGuariento/MIUI-XML-13-BRAZILIAN#2]
Please add MarkH-UK as collaborator to this repository.. 
it is needed to push auto fixes by translators.xiaomi.eu

same for MIUI 12 repository 

thank you

**Comment by ingbrzy** [comment]
https://translators.xiaomi.eu/XML_MIUI13-Brazilian-Portuguese-pt-rBR.html

https://translators.xiaomi.eu/XML_MIUI12-Brazilian-Portuguese-pt-rBR.html

**Comment by RicardoGuariento** [comment]
@ingbrzy I added MarkH-UK as collaborator on both repositories.

**Comment by ingbrzy** [comment]
Thanks!
