### ISSUE TITLE
Ajustar abreviações data na tela de bloqueio 

### ISSUE THREAD

**Issue by renatomars10** [RicardoGuariento/MIUI-XML-13-BRAZILIAN#6]
Você pode ajustar o formato da data para ficar no formato mais parecido com a global? Nome do dia e do mês inteiros não fica tão legal. 
![Screenshot_2022-08-27-06-09-08-282_com android systemui](https://user-images.githubusercontent.com/112246177/187023618-b8baf0c6-0ce0-42e9-80c8-caa706183b53.jpg)
![Screenshot_2022-08-27-06-08-01-587_com android systemui](https://user-images.githubusercontent.com/112246177/187023645-75c596f4-060c-4b35-a5a4-34223144c2cb.jpg)

**Comment by Feurrado** [comment]
@RicardoGuariento @DiorgenesS 

Vocês fazem alguma ideia de qual pasta fica a string disso?

Procurei em outros repos (pt-pt, english, Hungarian) para ver se não é alguma linha faltando mas não achei nada relacionado a lock screen, talvez no app de temas?

Se alguém souber da um toque que eu altero.

**Comment by KcNirvana** [comment]
> @RicardoGuariento @DiorgenesS
> 
> Vocês fazem alguma ideia de qual pasta fica a string disso?
> 
> Procurei em outros repos (pt-pt, english, Hungarian) para ver se não é alguma linha faltando mas não achei nada relacionado a lock screen, talvez no app de temas?
> 
> Se alguém souber da um toque que eu altero.

Boas,

    <string name="miui_lock_screen_date">"EEEE, d 'de' MMMM"</string>
    <string name="miui_lock_screen_date_12">"EEEE, d 'de' MMMM"</string>
    <string name="miui_lock_screen_date_two_lines">"EEEE d 'de' MMMM"</string>
    <string name="miui_lock_screen_date_two_lines_12">"EEEE d 'de' MMMM"</string>
    <string name="miui_lock_screen_large_date">"EEEE d 'de' MMMM"</string>
    <string name="miui_lock_screen_large_date_12">"EEEE d 'de' MMMM"</string>

https://github.com/RicardoGuariento/MIUI-XML-13-BRAZILIAN/blob/31123cfe23c868acb693c9ff82b0d35607573d79/Brazilian-Portuguese/main/MiuiSystemUI.apk/res/values-pt-rBR/strings.xml

Abraço

**Comment by renatomars10** [comment]
Na Global é esse formato. 
![20200630163653](https://user-images.githubusercontent.com/112246177/190930765-b172e176-df12-4b20-83c0-1b1b11502c4e.jpg)

**Comment by Feurrado** [comment]
@KcNirvana 

Obrigado meu caro!

**Comment by Feurrado** [comment]
Fixed!

Se na próxima atualização ainda estiver incorreto, abra outro chamado.

:)
