### ISSUE TITLE
Problema no Toast

### ISSUE THREAD

**Issue by LuizDumont** [RicardoGuariento/MIUI-XML-13-BRAZILIAN#7]
De um tempo pra cá percebi que a MIUI está com um certo problema.
Quando aparece um toast na tela, não é possível pressionar os botões próximo ao toast enquanto ele não desaparecer.

Isso é inconveniente e tira a paciência quando você está focado em digitar algo e aparece um toast na frente.
Problema ocorre tanto no POCO F3 quanto no POCO F4 GT (não tive a oportunidade de testar em outros aparelhos).

**Comment by Feurrado** [comment]
Creio que isso não sejá problema na tradução e sim na UI do sistema, infelizmente por aqui não tem como fazer muito...
